[theme]
base = "dark"
primaryColor = "#3DD68C"
backgroundColor = "#0B1020"
secondaryBackgroundColor = "#121933"
textColor = "#E5E9F2"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true
